import Head from 'next/head'
import Image from 'next/image'
import { DuelInput } from '../components'


export default function Home({TOKEN}) {
  return (
    <div className="bg-slate-600 h-screen ">
      <Head>
        <title>GitHub Duel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="text-white py-2 px-4 text-2xl text-center">
      GitHub Duel
      </header>
      <main className=''>
        <DuelInput TOKEN={TOKEN}/>
      </main>

      <footer className="">
      
      </footer>
    </div>
  )

}

export async function getStaticProps() {

  const TOKEN= await (process.env.REACT_APP_TOKEN);
  return {
      props : {
          TOKEN,
      }
  }
 
}
