import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div className="bg-black h-screen ">
      <Head>
        <title>GitHub Duel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="text-white py-2 px-4">
      GitHub Duel
      </main>

      <footer className="">
      
      </footer>
    </div>
  )
}
